accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),
    path('<username>/follow_list/', views.follow_list, name='follow_list'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<article_pk>/', views.detail, name='detail'),
    path('<article_pk>/update/', views.update, name='update'),
    path('<article_pk>/delete/', views.delete, name='delete'),
    path('<article_pk>/comments_create', views.comments_create, name='comments_create'),
    path('<article_pk>/<comment_pk>/comments_delete', views.comments_delete, name='comments_delete'),
    path('<article_pk>/like/', views.like, name='like'),
    path('<article_pk>/like_list/', views.like_list, name='like_list'),

]

instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('community.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

community/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 원본 그대로
    image = models.ImageField()
    # DB 저장 X, 호출하게되면, 잘라서 표현
    image_thumbnail = ImageSpecField(source='image',
                          processors=[Thumbnail(300, 300)],
                          format='JPEG',
                          options={'quality': 60})

    # 원본 잘라서 저장 : ProcessedImageField
    # image = ProcessedImageField(
    #                       processors=[ResizeToFill(100, 50)],
    #                       format='JPEG',
    #                       options={'quality': 60})

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles'
    )

class Comment(models.Model):
    # ("", null=True) => hides label
    content = models.CharField("", max_length=200,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

community/forms.py
from django import forms
# from crispy_forms.helper import FormHelper

from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'user', 'like_users',]

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from datetime import datetime, timedelta

def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'community/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('community:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)



@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect('community:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form,
            'article': article,
        }
        return render(request, 'community/form.html', context)


@login_required
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        article.delete()
    return redirect('community:index')


def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form,
    }
    return render(request, 'community/detail.html', context)

@require_POST
def comments_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('community:detail', article.pk)
    else:
        return redirect('accounts:login')

def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        return redirect('community:detail', article.pk)
    else:
        return redirect('accounts:login')

@login_required
def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if article.like_users.filter(id=user.pk).exists():
        article.like_users.remove(user)
    else:
        article.like_users.add(user)
    return redirect('community:detail', article.pk)

def like_list(request, article_pk):

    article = get_object_or_404(Article, pk=article_pk)
    l_list = article.like_users.all()
    context = {
        'article':article,
        'l_list':l_list,
    }
    return render(request, 'community/like_list.html', context)

community/templates/community/_comments.html
{% load crispy_forms_tags %}
<!--comment list-->

{% for comment in article.comment_set.all %}
<div class="d-flex justify-content-between">
    <a><b>{{ comment.user }}</b>  {{ comment.content }}</a>
    {% if comment.user == user %}
    <a href="{% url 'community:comments_delete' article.pk comment.pk %}">
        <button class="btn btn-danger btn-sm">delete</button>
    </a>
    {% endif %}
</div>
{% endfor %}



<!--new comment-->
<a>comment:</a><br>
<form action="{% url 'community:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    <a class="d-flex justify-content-between">
        {{ comment_form.content }}
        <input type="submit" value="post" class="btn btn-primary btn-sm">
    </a>
</form>

community/templates/community/_like.html
<!--likes : heart button-->
{% if request.user in article.like_users.all %}
    <a href="{% url 'community:like' article.pk %}">
        <i class="fas fa-heart text-danger"></i>
    </a>
{% else %}
    <a href="{% url 'community:like' article.pk %}">
        <i class="far fa-heart text-danger"></i>
    </a>
{% endif %}

<!--number of people who liked the post-->
{% if article.like_users.all|length > 1 %}
    <a class="text-dark text-decoration-none" href="{% url 'community:like_list' article.pk %}">{{ article.like_users.all|length }} likes</a>
{% else %}
    <a class="text-dark text-decortaion-none" href="{% url 'community:like_list' article.pk %}">{{ article.like_users.all|length }} like</a>
{% endif %}

community/templates/community/_post_nav.html
<!--id & post navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="{% url 'accounts:profile' article.user %}" class="navbar-brand text-dark text-decoration-none"><b>{{ article.user }}</b></a>
    {% if request.user == article.user %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item text-dark text-decoration-none" href="{% url 'community:update' article.pk %}">Edit</a>
          <a class="dropdown-item text-dark text-decoration-none" href="{% url 'community:delete' article.pk %}">Delete</a>
        </div>
      </li>
    </ul>
    {% endif %}
</nav>

community/templates/community/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="card">
    {% include 'community/_post_nav.html' %}
    <!--image-->
    <img src="{{ article.image.url }}" class="card-img-top" alt="...">
    <!--post content -->
    <div class="card-body">
        {% include 'community/_like.html' %}
        <p class="card-text">Title: {{ article.title }}</p>
        <p class="card-text">{{ article.content }}</p>

    	<p class="card-text"><small class="text-muted">Last updated at {{ article.updated_at }} | Created at {{ article.created_at }}</small></p>
        <hr>
        {% include 'community/_comments.html' %}
    </div>
</div>

{% endblock %}

community/templates/community/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
    <h2>New Post</h2>
    <form action="{% url 'community:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary btn-sm">Submit</button>
    </form>
    {% else %}
    <h2>Edit</h2>
        <form action="{% url 'community:update' article.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info btn-sm">Update</button>
    </form>
    {% endif %}

{% endblock %}

community/templates/community/index.html
{% extends 'base.html' %}
{% block body %}

{% for article in articles %}
    <div class="card">
        {% include 'community/_post_nav.html' %}
        <img src="{{ article.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            {% include 'community/_like.html' %}
            <p class="card-text"><a class="text-dark text-decoration-none" href="{% url 'community:detail' article.pk %}">Title: {{ article.title }}</a></p>
            <!--num of comments-->
            <p class="card-text">{{ article.comment_set.all|length }} comments</p>
            <!--updated time -->
    	    <p class="card-text"><small class="text-muted">Last updated at {{ article.updated_at }}</small></p>

        </div>
    </div>
{% endfor %}



{% endblock %}

community/templates/community/like_list.html
{% extends 'base.html' %}
{% block body %}

<h2>{{ article.user }}</h2>
{% for friend in l_list %}
    <a href="{% url 'accounts:profile' friend %}" class="my-3">{{ friend.username }}</a>

    <!--could follow or unfollow users from like list-->
    {% if friend == request.user %}
        <br>
    {% else %}
        {% if friend in request.user.followings.all %}
            <a href="{% url 'accounts:follow' friend.username %}" class="btn btn-sm btn-secondary my-3">unfollow</a>
            <br>

        {% else %}
            <a href="{% url 'accounts:follow' friend.username %}" class="btn btn-sm btn-primary my-3">follow</a>
            <br>
        {% endif %}
    {% endif %}
{% endfor %}

{% endblock %}